/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-11-22 12:20:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\n");
      out.write("    <meta name=\"description\" content=\"Aangetekende brief verzenden\">\n");
      out.write("    <meta name=\"author\" content=\"Zendu Aangetekende brieven versturen\">\n");
      out.write("    <title>Zendu | Aangetekende brief verzenden</title>\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"assets/css/bootstrap/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <!-- Retina.js - Load first for faster HQ mobile images. -->\n");
      out.write("    <script src=\"assets/js/plugins/retina/retina.min.js\"></script>\n");
      out.write("    <link href=\"favicon.ico\" rel=\"icon\" type=\"image/x-icon\" />\n");
      out.write("\t<link href=\"favicon.ico\" rel=\"shortcut icon\" type=\"image/x-icon\" />\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link href=\"assets/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <!-- Default Fonts -->\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Roboto:900,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,600,500,700,800,900' rel='stylesheet' type='text/css'>\n");
      out.write("    <!-- Modern Style Fonts (Include these is you are using body.modern!) -->\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>\n");
      out.write("    <!-- Vintage Style Fonts (Include these if you are using body.vintage!) -->\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Sanchez:400italic,400' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='https://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>\n");
      out.write("    <!-- Plugin CSS -->\n");
      out.write("    <link href=\"assets/css/plugins/owl-carousel/owl.carousel.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"assets/css/plugins/owl-carousel/owl.theme.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"assets/css/plugins/owl-carousel/owl.transitions.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"assets/css/plugins/magnific-popup.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"assets/css/plugins/background.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"assets/css/plugins/animate.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <!-- Vitality Theme CSS -->\n");
      out.write("    <!-- Uncomment the color scheme you want to use. -->\n");
      out.write("    <link href=\"assets/css/vitality-red.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <!-- <link href=\"assets/css/vitality-aqua.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- <link href=\"assets/css/vitality-blue.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- <link href=\"assets/css/vitality-green.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- <link href=\"assets/css/vitality-orange.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- <link href=\"assets/css/vitality-pink.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- <link href=\"assets/css/vitality-purple.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- <link href=\"assets/css/vitality-tan.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- <link href=\"assets/css/vitality-turquoise.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- <link href=\"assets/css/vitality-yellow.css\" rel=\"stylesheet\" type=\"text/css\"> -->\n");
      out.write("    <!-- IE8 support for HTML5 elements and media queries -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("</head>\n");
      out.write("<!-- Alternate Body Classes: .modern and .vintage -->\n");
      out.write("\n");
      out.write("<body id=\"page-top\">\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <!-- Note: navbar-default and navbar-inverse are both supported with this theme. -->\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top navbar-expanded\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand page-scroll\" href=\"#page-top\">\n");
      out.write("                    Zen<span style=\"color:firebrick\">du</span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                    <li class=\"hidden\">\n");
      out.write("                        <a class=\"page-scroll\" href=\"#page-top\"></a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#aangetekende\">Hoe werkt het</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#brief\">Starten</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#verzenden\">Over Ons</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#pricing\">Prijzen</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"page-scroll\" href=\"#contact\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-collapse -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container -->\n");
      out.write("    </nav>\n");
      out.write("    <header style=\"background-image: url('assets/img/bg-header.jpg');\">\n");
      out.write("        <div class=\"intro-content\">\n");
      out.write("<!--            <img src=\"assets/img/profile.png\" class=\"img-responsive img-centered\" alt=\"\">-->\n");
      out.write("            <div class=\"brand-name\">Zen<span style=\"color:firebrick\">du</span></div>\n");
      out.write("            <hr class=\"colored\">\n");
      out.write("            <div class=\"brand-name-subtext\">Aangetekende brieven digitaal <br>verzenden en beheren.</div>          \n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"login-form\">\n");
      out.write("            \n");
      out.write("            <form method=\"post\" action=\"login.jsp\" id=\"login_form\">\n");
      out.write("                <input id=\"email\" type=\"text\" class=\"login-input\" placeholder=\" email\" name=\"email\" tabindex=\"1\"></input><br>\n");
      out.write("                <input id=\"pass\" type=\"password\" class=\"login-input\" placeholder=\" paswoord\" name=\"pass\" tabindex=\"2\"></input><br>            \n");
      out.write("                <button id=\"login\" type=\"submit\" class=\"btn btn-outline-light page-scroll\" tabindex=\"3\" value=\"LOGIN\">Login</button>\n");
      out.write("                <div id=\"reset2\" class=\"btn btn-outline-light page-scroll\" tabindex=\"4\" style=\"display:none;\">Reset paswoord</div>\n");
      out.write("            </form>\n");
      out.write("            <br>\n");
      out.write("            ");
 String loginmessage = ""; if(null!=session.getAttribute("loginmessage")) loginmessage = (String)session.getAttribute("loginmessage");
      out.write("\n");
      out.write("            <a id=\"reset1\" href=\"#\" class=\"passwordlink\">");
      out.print(loginmessage);
      out.write("Paswoord vergeten?</a>\n");
      out.write("            <a id=\"back1\" href=\"#\" class=\"passwordlink\" style=\"display:none;\">Terug naar login scherm</a>\n");
      out.write("        </div>\n");
      out.write("    \n");
      out.write("        <div class=\"getstarted-form\">\n");
      out.write("            \n");
      out.write("        <form><a class=\"page-scroll login-btn\" href=\"#brief\">Start gratis</a>\n");
      out.write("        </form>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"scroll-down\">\n");
      out.write("            <a class=\"btn page-scroll\" href=\"#aangetekende\"><i class=\"fa fa-angle-down fa-fw\"></i></a>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <section id=\"aangetekende\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row text-center\">\n");
      out.write("                <div class=\"col-lg-12 wow fadeIn\">\n");
      out.write("                    <h1>Hoe werkt het?</h1>\n");
      out.write("                    <p>Wij printen uw aangetekende brief en versturen aangetekend.</p>\n");
      out.write("                    <hr class=\"colored\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row text-center content-row\">\n");
      out.write("                <div class=\"col-md-3 col-sm-6 wow fadeIn\" data-wow-delay=\".2s\">\n");
      out.write("                    <div class=\"about-content\">\n");
      out.write("                        <i class=\"fa fa-eye fa-4x\"></i>\n");
      out.write("                        <h3>U schrijft de brief en laadt hem op op de website.</h3>\n");
      out.write("                        <p>Opladen is eenvoudig, we aanvaarden brieven in PDF formaat. </p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6 wow fadeIn\" data-wow-delay=\".4s\">\n");
      out.write("                    <div class=\"about-content\">\n");
      out.write("                        <i class=\"fa fa-edit fa-4x\"></i>\n");
      out.write("                        <h3>Wij printen uw brief en versturen hem aangetekend via de reguliere post.</h3>\n");
      out.write("                        <p>Brieven opgeladen voor 15u00 worden dezelfde werkdag nog verstuurd, na 15u00 de volgende werkdag.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6 wow fadeIn\" data-wow-delay=\".6s\">\n");
      out.write("                    <div class=\"about-content\">\n");
      out.write("                        <i class=\"fa fa-tablet fa-4x\"></i>\n");
      out.write("                        <h3>Het verzendingsbewijs is digitaal beschikbaar in uw applicatie.</h3>\n");
      out.write("                        <p>Het verzendingsbewijs wordt door ons gearchiveerd en ingescand. Met uw persoonlijk inlog kan u al uw verstuurde brieven en bijhorende verzendingsbewijzen raadplegen.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6 wow fadeIn\" data-wow-delay=\".8s\">\n");
      out.write("                    <div class=\"about-content\">\n");
      out.write("                        <i class=\"fa fa-heart fa-4x\"></i>\n");
      out.write("                        <h3>De geadresseerde ontvangt zijn aangetekende brief.</h3>\n");
      out.write("                        <p>Op dezelfde manier alsof u de brief zelf naar het postkantoor had gebracht.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <aside class=\"cta-quote\" style=\"background-image: url('assets/img/bg-aside.jpg');\">\n");
      out.write("        <div class=\"container wow fadeIn\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-10 col-md-offset-1\">\n");
      out.write("                    <span class=\"quote\">Verzend <span class=\"text-primary\">digitaal.</span> Legale aangetekende brieven. Beheer van de brieven op een eenvoudige manier.</span>\n");
      out.write("                    <hr class=\" colored\">\n");
      out.write("                    <a class=\"btn btn-outline-light page-scroll\" href=\"#brief\">Gratis starten</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </aside>\n");
      out.write("    <section id=\"brief\" class=\"services\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row text-center\">\n");
      out.write("                <div class=\"col-lg-12 wow fadeIn\">\n");
      out.write("                    <h2>starten</h2>\n");
      out.write("                    <hr class=\"colored\">\n");
      out.write("                    <p>Probeer het uit en verzend 1 gratis aangetekende brief.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row content-row\">\n");
      out.write("                \n");
      out.write("              <form id=\"upload\" action=\"upload\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                <legend>Gegevens bestemmeling</legend>\n");
      out.write("                <div class=\"form-group\">             \n");
      out.write("                  <input type=\"text\" class=\"form-control valid\" name=\"destinationfirstname\" id=\"destinationfirstname\" placeholder=\"Voornaam\" style=\"width:40%\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"destinationlastname\" id=\"destinationlastname\" placeholder=\"Naam\" style=\"width:40%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">             \n");
      out.write("                  <input type=\"text\" class=\"form-control valid\" name=\"destinationcompany\" id=\"destinationcompany\" placeholder=\"Bedrijf\" style=\"width:40%\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"destinationstreetname\" id=\"destinationstreetname\" placeholder=\"Straatnaam\"style=\"width:70%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"destinationstreetnumber\" id=\"destinationstreetnumber\" placeholder=\"Straatnummer\" style=\"width:15%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"destinationzipcode\" id=\"destinationzipcode\" placeholder=\"Postcode\" style=\"width:20%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"destinationcity\" id=\"destinationcity\" placeholder=\"Stad\" style=\"width:40%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"email\" class=\"form-control valid\" name=\"destinationEmail\" id=\"destinationEmail\" placeholder=\"E-mail adres\" style=\"width:40%\">\n");
      out.write("                </div>\n");
      out.write("                <legend>Te verzenden document</legend>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input id=\"file\" name=\"file\" type=\"file\" class=\"file\" accept=\"application/pdf\">\n");
      out.write("                  <span class=\"error\"><br>We aanvaarden enkel PDF documenten, omdat we enkel zo kunnen garanderen dat uw opmaak exact behouden blijft.<br>Dus graag uw document eerst opslaan in PDF formaat voor u het oplaadt.</span>\n");
      out.write("                </div>\n");
      out.write("                <legend>Uw gegevens</legend>\n");
      out.write("                <div class=\"form-group\">             \n");
      out.write("                  <input type=\"text\" class=\"form-control valid\" name=\"senderfirstname\" id=\"senderfirstname\" placeholder=\"Voornaam\" style=\"width:40%\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"senderlastname\" id=\"senderlastname\" placeholder=\"Naam\" style=\"width:40%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">             \n");
      out.write("                  <input type=\"text\" class=\"form-control valid\" name=\"sendercompany\" id=\"sendercompany\" placeholder=\"Bedrijf\" style=\"width:40%\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">             \n");
      out.write("                  <input type=\"text\" class=\"form-control valid\" name=\"sendervat\" id=\"sendervat\" placeholder=\"BTW-nummer\" style=\"width:40%\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"senderstreetname\" id=\"senderstreetname\" placeholder=\"Straatnaam\" style=\"width:70%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"senderstreetnumber\" id=\"senderstreetnumber\" placeholder=\"Straatnummer\" style=\"width:15%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"senderzipcode\" id=\"senderzipcode\" placeholder=\"Postcode\" style=\"width:20%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control required\" name=\"sendercity\" id=\"sendercity\" placeholder=\"Stad\" style=\"width:40%\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input id=\"senderemail\" type=\"email\" class=\"form-control required\" name=\"senderemail\" placeholder=\"E-mail adres\" style=\"width:40%\">\n");
      out.write("                  <span class=\"error\">Gelieve een geldig email adres in te geven</span>\n");
      out.write("                  <p class=\"error\"><br>Dit e-mail adres is reeds geregistreerd. <br>Kies een ander e-mail adres of login hierboven. </p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input id=\"senderpassword\" type=\"password\" class=\"form-control required\" name=\"senderpassword\" placeholder=\"Kies een paswoord\">\n");
      out.write("                  <span class=\"error\">Dit is een verplicht veld</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input id=\"senderpasswordcheck\" type=\"password\" class=\"form-control required valid\" name=\"senderpasswordcheck\" placeholder=\"Herhaal het paswoord\">\n");
      out.write("                  <p class=\"error\"><br>De door u ingevulde paswoorden verschillen. Graag even nakijken aub.</p>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"success_test\"></div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input id=\"payment_test\" type=\"submit\" class=\"btn btn-lg btn-default\" value=\"verzenden\"/>\n");
      out.write("                  <a id=\"closebutton\" class=\"btn btn-lg btn-default\">Cancel</a><br>\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section id=\"verzenden\" class=\"bg-gray\">\n");
      out.write("        <div class=\"container text-center wow fadeIn\">\n");
      out.write("            <h2>Over ons</h2>\n");
      out.write("            <hr class=\"colored\">\n");
      out.write("            <p style=\"text-align:left\">We zijn ervan overtuigd dat het verzenden van aangetekende brieven makkelijker moet kunnen. De verplichte trip naar het postkantoor is tijdrovend en onefficiÃ«nt.</p>\n");
      out.write("            <p style=\"text-align:left\">Maar ook het beheer van de verstuurde brieven kan beter en vooral eenvoudiger. Het huidig systeem van afgestempelde bewijsstrookjes is achterhaald, omslachtig en werkt fouten in de hand.</p>\n");
      out.write("            <p style=\"text-align:left\">Dat kan beter.  We maakten daarom een toepassing die u toelaat uw brief in pdf formaat op te laden en waarbij wij de verdere stappen van het proces van aangetekende verzending afhandelen. Resultaat: tijdswinst, foutloze afhandeling en efficiÃ«nt beheer van bewijs.</p>\n");
      out.write("            <p style=\"text-align:left\">Daarnaast willen we nog een stap verder gaan. De EU Richtlijn 910/2014 laat toe om op legale wijze aangetekende brieven via elektronische weg te verzenden en dit vanaf 1 juli 2016. Onze technologie laat toe om tegen dan het volledig automatisch elektronische behandelen van uw aangetekende brief.\n");
      out.write("            Dit betekent een fundamenteel lagere kostprijs, een snellere afhandeling Ã©n aangetekende brieven verzenden binnen heel Europa.</p>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section id=\"pricing\" class=\"pricing\" style=\"background-image: url('assets/img/bg-pricing.jpg')\">\n");
      out.write("        <div class=\"container wow fadeIn\">\n");
      out.write("            <div class=\"row text-center\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <h2>Prijzen</h2>\n");
      out.write("                    <hr class=\"colored\">\n");
      out.write("                    <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum, quae, laborum, voluptate delectus odio doloremque error porro obcaecati nemo animi ducimus quaerat nostrum? Ab molestiae eaque et atque architecto reiciendis.</p>-->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row content-row\">\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"pricing-item featured-first\">\n");
      out.write("                        <h3>Basic</h3>\n");
      out.write("                        <hr class=\"colored\">\n");
      out.write("                        <div class=\"price\"><span class=\"number\">9.80<sup>&euro;</sup></span> / brief</div>\n");
      out.write("                        <ul class=\"list-group\">\n");
      out.write("                            <li class=\"list-group-item\">1 individuele brief</li>\n");
      out.write("                            <li class=\"list-group-item\">Maximum 10 pagina's</li>\n");
      out.write("                            <li class=\"list-group-item\">Opgeladen voor 15u00, dezelfde dag aangetekend verzonden</li>\n");
      out.write("                            <li class=\"list-group-item\">Uw eerste aangetekende brief is gratis</li>\n");
      out.write("                        </ul>\n");
      out.write("                        <a href=\"#brief\" class=\"btn btn-outline-dark\">Starten</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"pricing-item featured\">\n");
      out.write("                        <h3>Plus</h3>\n");
      out.write("                        <hr class=\"colored\">\n");
      out.write("                        <div class=\"price\"><span class=\"number\">8.80<sup>&euro;</sup></span> / brief</div>\n");
      out.write("                        <ul class=\"list-group\">\n");
      out.write("                            <li class=\"list-group-item\">Pakket van <strong>10</strong> brieven</li>\n");
      out.write("                            <li class=\"list-group-item\">Totaal: 88 &euro;, inc. BTW</li>\n");
      out.write("                            <li class=\"list-group-item\">Opgeladen voor 15u00, dezelfde dag aangetekend verzonden</li>\n");
      out.write("                        </ul>\n");
      out.write("                        <a href=\"#\" class=\"btn btn-outline-dark\">Log in om te bestellen</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"pricing-item featured-last\">\n");
      out.write("                        <h3>Premium</h3>\n");
      out.write("                        <hr class=\"colored\">\n");
      out.write("                        <div class=\"price\"><span class=\"number\">8.50<sup>&euro;</sup></span> / brief</div>\n");
      out.write("                        <ul class=\"list-group\">\n");
      out.write("                            <li class=\"list-group-item\">Pakket van 50 brieven</li>\n");
      out.write("                            <li class=\"list-group-item\">Totaal: 425 &euro;, inc. BTW</li>\n");
      out.write("                            <li class=\"list-group-item\">Opgeladen voor 15u00, dezelfde dag aangetekend verzonden</li>\n");
      out.write("                        </ul>\n");
      out.write("                        <a href=\"#\" class=\"btn btn-outline-dark\">Log in om te bestellen</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"cta-form bg-dark\">\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("            <h3>Laat je e-mail hieronder achter.</h3>\n");
      out.write("            <hr class=\"colored\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-8 col-lg-offset-2\">\n");
      out.write("                    <!-- MailChimp Signup Form -->\n");
      out.write("                    <div id=\"mc_embed_signup\">\n");
      out.write("                        <!-- Replace the form action in the line below with your MailChimp embed action! For more informatin on how to do this please visit the Docs! -->\n");
      out.write("                            <div class=\"input-group input-group-lg\">\n");
      out.write("                                <input type=\"email\" name=\"EMAIL\" class=\"form-control\" id=\"mce-EMAIL\" placeholder=\"Email address...\">\n");
      out.write("                                <span class=\"input-group-btn\">\n");
      out.write("                                    <button type=\"submit\" name=\"subscribe\" id=\"mc-embedded-subscribe\" class=\"btn btn-primary\">Hou me op de hoogte!</button>\n");
      out.write("                                </span>\n");
      out.write("                            </div>\n");
      out.write("                            <div id=\"mce-responses\">\n");
      out.write("                                <div class=\"response\" id=\"mce-error-response\" style=\"display:none\"></div>\n");
      out.write("                                <div class=\"response\" id=\"mce-success-response\" style=\"text-align:left;\"></div>\n");
      out.write("                            </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- End MailChimp Signup Form -->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section id=\"contact\">\n");
      out.write("        <div class=\"container wow fadeIn\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12 text-center\">\n");
      out.write("                    <h2>Contacteer ons</h2>\n");
      out.write("                    <hr class=\"colored\">\n");
      out.write("                    <p></p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row content-row\">\n");
      out.write("                <div class=\"col-lg-8 col-lg-offset-2\">\n");
      out.write("                    <form name=\"sentMessage\" id=\"contactForm\" novalidate>\n");
      out.write("                        <div class=\"row control-group\">\n");
      out.write("                            <div class=\"form-group col-xs-12 floating-label-form-group controls\">\n");
      out.write("                                <label>Naam</label>\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Naam\" id=\"name\" required data-validation-required-message=\"Laat uw naam achter aub.\">\n");
      out.write("                                <p class=\"help-block text-danger\"></p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row control-group\">\n");
      out.write("                            <div class=\"form-group col-xs-12 floating-label-form-group controls\">\n");
      out.write("                                <label>Email Adres</label>\n");
      out.write("                                <input type=\"email\" class=\"form-control\" placeholder=\"Email\" id=\"email\" required data-validation-required-message=\"Laat uw email achter aub.\">\n");
      out.write("                                <p class=\"help-block text-danger\"></p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row control-group\">\n");
      out.write("                            <div class=\"form-group col-xs-12 floating-label-form-group controls\">\n");
      out.write("                                <label>Telefoonnummer</label>\n");
      out.write("                                <input type=\"tel\" class=\"form-control\" placeholder=\"Telefoonnummer\" id=\"phone\">\n");
      out.write("                                <p class=\"help-block text-danger\"></p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row control-group\">\n");
      out.write("                            <div class=\"form-group col-xs-12 floating-label-form-group controls\">\n");
      out.write("                                <label>Boodschap</label>\n");
      out.write("                                <textarea rows=\"5\" class=\"form-control\" placeholder=\"Boodschap\" id=\"message\" required data-validation-required-message=\"Laat een boodschap achter aub.\"></textarea>\n");
      out.write("                                <p class=\"help-block text-danger\"></p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <br>\n");
      out.write("                        <div id=\"success\"></div>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"form-group col-xs-12\">\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-outline-dark\">Verzenden</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <footer class=\"footer\" style=\"background-image: url('assets/img/bg-footer.jpg')\">\n");
      out.write("        <div class=\"container text-center\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-4 contact-details\">\n");
      out.write("                    <h4><i class=\"fa fa-phone\"></i> Call</h4>\n");
      out.write("                    <p>0489 62 19 67</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 contact-details\">\n");
      out.write("                    <h4><i class=\"fa fa-map-marker\"></i> Visit</h4>\n");
      out.write("                    <p>Huybrechtsstraat 76\n");
      out.write("                        <br>2140 Borgerhout</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 contact-details\">\n");
      out.write("                    <h4><i class=\"fa fa-envelope\"></i> Email</h4>\n");
      out.write("                    <p><a href=\"mailto:mail@example.com\">info@zendu.be</a>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row social\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <ul class=\"list-inline\">\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-facebook fa-fw fa-2x\"></i></a>\n");
      out.write("                        </li>\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-twitter fa-fw fa-2x\"></i></a>\n");
      out.write("                        </li>\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-linkedin fa-fw fa-2x\"></i></a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row copyright\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <p class=\"small\">&copy; 2015 Zendu.be Aangetekende brieven</p>\n");
      out.write("                    <p class=\"small\"><a href=\"disclaimer.html\">Disclaimer</a> &nbsp &nbsp <a href=\"cookies.html\">Cookies Policy</a></p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("    <!-- Core Scripts -->\n");
      out.write("    <script src=\"assets/js/jquery.js\"></script>\n");
      out.write("    <script src=\"assets/js/bootstrap/bootstrap.min.js\"></script>\n");
      out.write("    <!-- Plugin Scripts -->\n");
      out.write("    <script src=\"assets/js/plugins/jquery.easing.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/classie.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/cbpAnimatedHeader.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/owl-carousel/owl.carousel.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/jquery.magnific-popup/jquery.magnific-popup.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/background/core.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/background/transition.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/background/background.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/jquery.mixitup.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/wow/wow.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/contact_me.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins/jqBootstrapValidation.js\"></script>\n");
      out.write("    <!-- Vitality Theme Scripts -->\n");
      out.write("    <script src=\"assets/js/vitality.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
