/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-10-14 12:28:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class new_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    if ((session.getAttribute("userid") == null) || (session.getAttribute("userid") == "")) {

      out.write("\n");
      out.write("You are not logged in<br/>\n");
      out.write("<a href=\"index.jsp\">Please Login</a>\n");
} else {
    String userid = (String)session.getAttribute("userid");
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/c9", "janblonde", "");
    Statement st = con.createStatement();
    ResultSet rs1;
    rs1 = st.executeQuery("select * from Members where email='" + userid + "';");
    if (rs1.next()){ 
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("      <section class=\"module content\">\n");
      out.write("        <div id=\"form1\" class=\"container\">\n");
      out.write("          <h2>Document verzenden</h2>\n");
      out.write("            <div class=\"well bs-component\">                      \n");
      out.write("              <form action=\"upload\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("                <legend>Gegevens bestemmeling</legend>\n");
      out.write("                <div class=\"form-group\">             \n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"destinationfirstname\" placeholder=\"Voornaam\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"destinationlastname\" placeholder=\"Naam\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"destinationstreetname\" placeholder=\"Straatnaam\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"destinationstreetnumber\" placeholder=\"Straatnummer\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"destinationzipcode\" placeholder=\"Postcode\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"destinationcity\" placeholder=\"Stad\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"email\" class=\"form-control\" name=\"destinationEmail\" placeholder=\"E-mail adres\">\n");
      out.write("                </div>\n");
      out.write("                <legend>Te verzenden document</legend>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input id=\"input-1\" name=\"file\" type=\"file\" class=\"file\">\n");
      out.write("                </div>\n");
      out.write("                <legend>Uw gegevens</legend>\n");
      out.write("                <div class=\"form-group\">             \n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"senderfirstname\" placeholder=\"Voornaam\" value=\"");
      out.print(rs1.getString("first_name"));
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"senderlastname\" placeholder=\"Naam\" value=\"");
      out.print(rs1.getString("last_name"));
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"senderstreetname\" placeholder=\"Straatnaam\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"senderstreetnumber\" placeholder=\"Straatnummer\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">              \n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"senderzipcode\" placeholder=\"Postcode\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"sendercity\" placeholder=\"Stad\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <input type=\"submit\" class=\"btn btn-lg btn-default\" value=\"verzenden\"/>\n");
      out.write("                  <a id=\"closebutton\" class=\"btn btn-lg btn-default\">Cancel</a><br>\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("</body>\n");
      out.write("</html>\n");
}}
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
