/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-10-15 09:20:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.security.*;
import java.math.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.security");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.math");
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

if ((session.getAttribute("userid") == null) || (session.getAttribute("userid") == "")) {

      out.write("\n");
      out.write("You are not logged in<br/>\n");
      out.write("<a href=\"index.html\">Please Login</a>\n");
}
String orderID = (String)request.getAttribute("orderid");

String text = "AMOUNT=980weliveinnumber76CURRENCY=EURweliveinnumber76LANGUAGE=en_USweliveinnumber76ORDERID="+ orderID +"weliveinnumber76PSPID=zenduweliveinnumber76";

MessageDigest crypt = MessageDigest.getInstance("SHA-1");
crypt.reset();
crypt.update(text.getBytes("UTF-8"));

String result = new BigInteger(1, crypt.digest()).toString(16);

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<p>Payment ");
      out.print( result );
      out.write("</p>\n");
      out.write("<FORM METHOD=\"post\" ACTION=\"https://secure.ogone.com/ncol/test/orderstandard.asp\" id=form1 name=form1>\n");
      out.write("<INPUT NAME=\"PSPID\" value=\"zendu\">\n");
      out.write("<INPUT NAME=\"orderID\" VALUE=\"");
      out.print(orderID);
      out.write("\">\n");
      out.write("<INPUT NAME=\"amount\" VALUE=\"980\">\n");
      out.write("<INPUT NAME=\"currency\" VALUE=\"EUR\">\n");
      out.write("<INPUT NAME=\"language\" VALUE=\"en_US\">\n");
      out.write("<!-- lay out information -->\n");
      out.write("\n");
      out.write("<!--<INPUT type=\"hidden\" NAME=\"MANDATEID\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"SIGNDATE\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"SEQUENCETYPE\" VALUE=\"\">\n");
      out.write("\n");
      out.write("<INPUT type=\"hidden\" NAME=\"TITLE\" VALUE=\"PAYMENT\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"BGCOLOR\" VALUE=\"#4e84c4\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"TXTCOLOR\" VALUE=\"#FFFFFF\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"TBLBGCOLOR\" VALUE=\"#FFFFFF\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"TBLTXTCOLOR\" VALUE=\"#000000\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"BUTTONBGCOLOR\" VALUE=\"#00467F\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"BUTTONTXTCOLOR\" VALUE=\"#FFFFFF\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"LOGO\" VALUE=\"<fill here your logo file name>\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"FONTTYPE\" VALUE=\"Verdana\">-->\n");
      out.write("\n");
      out.write("<INPUT type=\"hidden\" NAME=\"SHASIGN\" VALUE=\"");
      out.print( result );
      out.write("\">\n");
      out.write("<!-- or dynamic template page\n");
      out.write("<INPUT type=\"hidden\" NAME=\"TP\" VALUE=\"<fill here your template page>\">\n");
      out.write("\n");
      out.write("<INPUT type=\"hidden\" NAME=\"ACCEPTURL\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"declineurl\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"exceptionurl\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"cancelurl\" VALUE=\"\">\n");
      out.write("\n");
      out.write("<INPUT type=\"hidden\" NAME=\"COM\" VALUE=\"<fill here your order description>\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"CN\" VALUE=\"<fill here your Client name>\">\n");
      out.write("<INPUT type=\"hidden\" name=\"EMAIL\" value=\"<fill here your Client email>\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"PM\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"BRAND\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"ownerZIP\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"owneraddress\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"owneraddress2\" VALUE=\"\">\n");
      out.write("<INPUT type=\"hidden\" NAME=\"owneraddress3\" VALUE=\"\">-->\n");
      out.write("<input type=\"submit\" value=\"SUBMIT\" id=submit2 name=submit2>\n");
      out.write("</form>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
